export default function Head() {
  return (
    <>
      <title>Ecommerce</title>
      <link rel="icon" href="favicon.ico?" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src https://accounts.google.com; child-src 'none'; object-src 'none'" />

      <meta name="description" content="Generated by create next app" />
    </>
  );
};
